### ISSUE TITLE
Issue in Hello World Program

### ISSUE THREAD

**Issue by Danish734-oss** [Danish734-oss/cpp-programs#1]
I have recently uploaded my new program [378a87a](https://github.com/Danish734-oss/cpp-programs/commit/378a87a0816df92a8e7930a9a4499640b30f5a1f) and having issue in running it, I cant understand the error can anyone fix it for me please?

**Comment by HammadMaqbool** [comment]
Let me try and I will send you a PR

**Comment by Danish734-oss** [comment]
Sure I am waiting. . .
